apiVersion: batch/v1
kind: Job
metadata:
  name: fashionova-job
spec:
  template:
    spec:
      containers:
      - name: fashionova-job
        image: yash5090/fashionova:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
