apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashionova-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: fashionova
  template:
    metadata:
      labels:
        app: fashionova
    spec:
      containers:
        - name: fashionova
          image: yash5090/fashionova:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
